# -*- coding: utf-8 -*-
"""ACT 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12E6rtbLhK6eMgJv24pLq6bl-GW4Igg2j

Este es un ejercicio para probar la herramienta google Colaboratory con CUADERNOS DE JUPITER para aprender algo de Python con ejemplos de algoritmos simples

El ejercicio anterior permite visualizar una suma de dos variables que nunca cambian de valor porque son asignadas en un momento de programa.
Al final muestra la suma de los dos valores (se visualiza unicamente en cuadernos de jupiter)

Vamos a modificar el programa para que el sistema permita la entrada de los datos que requieren ser sumados.
Recordar la estructura básica de un programa: entradas, procesos y salidas.
"""

#ESTE EJERCICIO EFECTUA LA SUMA DE DOS VARIABLES (A Y B)
# incorporamos una instrucción para carga de datos (entrada de valores)
A= input()
B= input()
A + B

"""El anterior ejercicio es muy básico no ayuda al usuario porque no le orienta en lo que debe hacer sería importante que le dijera en texto ingrese un número"""

#ESTE EJERCICIO EFECTUA LA SUMA DE DOS VARIABLES (A Y B)
# incorporamos una instrucción para carga de datos (entrada de valores)
A= input("ingrese el número A...")
B= input("Ingrese el número B...")
A + B

"""Observe que el sistema genera como resultado una CADENA DE TEXTO (entre comillas) mostrando los numeros 5 y 6 como si fuesen letras o simbolos, no como una cantidad o valor numerico.

También observe que no haya una ayuda para el usuario, indicando que esta es la respuesta, solo muestra el dato resultante de la operación de suma (observe que el resultado se muestra entre comillas), por lo cual debo hacer unos correctivos
"""

#ESTE EJERCICIO EFECTUA LA SUMA DE DOS VARIABLES (A Y B)
# incorporamos una instrucción para carga de datos (entrada de valores)

#para que los datos leidos se manejen como valor numerico debe convertirse a numero utilizando la instruccion o funcion Int
A= int(input("ingrese el número A..."))
B= int(input("Ingrese el número B..."))
A + B

"""Es momento de mejorar el codigo para que se utilice correctamente la estructura de un programa de computo, es ddecir, en orden se apliquen LAS ENTRADAS DE DATOS, SE EJCUTEN LOS PROCESOS y finalmente SE MUESTREN LAS SALIDAS O RESULTADOS
Para ello lo recomendable es utilizar una función para generar las salidas de datos en pantalla (print)
"""

#ESTE EJERCICIO EFECTUA LA SUMA DE DOS VARIABLES (A Y B)
# incorporamos una instrucción para carga de datos (entrada de valores)

#para que los datos leidos se manejen como valor numerico debe convertirse a numero utilizando la instruccion o funcion Int
A= int(input("ingrese el número A..."))
B= int(input("Ingrese el número B..."))
A + B

#Realizamos el proceso utilizando una variable para almacenar el resultado de la suma
SUMA = A + B

#Mejoramos la salida utilizando una instrucción que dirija la salida a la pantalla de consola
print(SUMA)

"""Mejoramos la salida incorporando algunas expresiones en texto que le ayudan al usuario a entender el ejercicio con una ayuda visual que le muestra que la cifra es la suma de los valores ingresados"""

#ESTE EJERCICIO EFECTUA LA SUMA DE DOS VARIABLES (A Y B)
# incorporamos una instrucción para carga de datos (entrada de valores)

#para que los datos leidos se manejen como valor numerico debe convertirse a numero utilizando la instruccion o funcion Int
A= int(input("ingrese el número A..."))
B= int(input("Ingrese el número B..."))
A + B

#Realizamos el proceso utilizando una variable para almacenar el resultado de la suma
SUMA = A + B

#Mejoramos la salida utilizando una instrucción que dirija la salida a la pantalla de consola
#Y mostramos el texto que ayuda o indica que la cifra mostrada como salida corresponde con la suma de los dos numeros
print("El resultado de la suma de los numeros A y B es ...",SUMA)

"""Mejoremos el ejercicio colocando en la respuesta también el valor de los números ingresados"""

#ESTE EJERCICIO EFECTUA LA SUMA DE DOS VARIABLES (A Y B)
# incorporamos una instrucción para carga de datos (entrada de valores)

#para que los datos leidos se manejen como valor numerico debe convertirse a numero utilizando la instruccion o funcion Int
A= int(input("ingrese el número A..."))
B= int(input("Ingrese el número B..."))
A + B

#Realizamos el proceso utilizando una variable para almacenar el resultado de la suma
SUMA = A + B

#Mejoramos la salida utilizando una instrucción que dirija la salida a la pantalla de consola
#Y mostramos el texto que ayuda o indica que la cifra mostrada como salida corresponde con la suma de los dos numeros
#Adicional mostramos los valores que conforman la suma
print("El resultado de la suma de los numeros A (",A,") y el número B(",B,") es..",SUMA)

"""SEGUNDO EJERCICIO
Solucion algoritmo de calculo de area de figura geometrica trapezoidal
"""

#Leer los datos de entrada
A = int(input("Ingrese medida de la altura mayor de la figura..."))
B = int(input("Ingrese medida de la base de la figura..."))
C = int(input("Ingrese medida de la altura menor de la figura..."))

#Ejecutamos los procesos
AT = (B*(A-C))/2
AR = B * C
Area = AT + AR

#Se muestran los resultados (salidas del sistema)

print("El area total de la figura es..",Area)

"""Vamos a mejorar los textos para ayudar al usuario en su experiencia con el sistema...
Incorporamos un titulo y datos como la unidad de medida
"""

#Leer los datos de entrada
print("Sistema para calcular area de terrenos trapezoidales\n--------------------------\n","ingrese cifras en metros cuadrados")
A = int(input("Ingrese medida de la altura mayor de la figura..."))
B = int(input("Ingrese medida de la base de la figura..."))
C = int(input("Ingrese medida de la altura menor de la figura..."))

#Ejecutamos los procesos
AT = (B*(A-C))/2
AR = B * C
Area = AT + AR

#Se muestran los resultados (salidas del sistema)

print("El area total de la figura es..",Area,"metros cuadrados")